
services:
  app:
    build: ./app
    networks:
      - z-server-bridge
    working_dir: /home/node/app
    volumes:
      - ../:/home/node/app
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
      - /etc/localtime:/etc/localtime:ro
    command: sleep infinity
    ports:
    - '3000:3000'
  redis:
    build: ./redis
    networks:
      - z-server-bridge
    #ports:
      #- '6379:6379'

networks:
  z-server-bridge:
    name: z-server-bridge
    driver: bridge
